### ISSUE TITLE
Composer checksum problem

### ISSUE THREAD

**Issue by acidjunk** [cedricblondeau/magento2-ansible-vagrant#2]
This seems  a really nice way to setup magento2. 

When I run the vagrant up it fails in Ansible task: 

> TASK [php : Download installer]

Error message:
    "msg": "The checksum for /home/vagrant/composer-setup.php did not match e115a8dc7871f15d853148a7fbac7da27d6c0030b848d9b3dc09e2a0388afed865e6a3d6b3c0fad45c48e2b5fc1196ae; it was 669656bab3166a7aff8a7506b8cb2d1c292f042046c5a994c43155c0be6190fa0355160742ab2e1c88d40d5be660b410."

**Comment by cedricblondeau** [comment]
Thanks for reporting this.
I updated the composer checksum, it's fixed: 9075d1d938f3ec843ccca561dc860dc452c31843

**Comment by acidjunk** [comment]
Great; tested it : works like a charm :)
